### ISSUE TITLE
Unit tests appear to be broken

### ISSUE THREAD

**Issue by ciband** [ArkEcosystem/arky#127]
Unit test discovery appears to be broke due to something in the arky/test/ark/test_v2.py file.

I do not know the environment well enough to know what the issue is.

Error List:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 406, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 406, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 452, in _find_test_path
    return self.loadTestsFromModule(module, pattern=pattern), False
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 123, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\loader.py", line 92, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\suite.py", line 24, in __init__
    self.addTests(tests)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\suite.py", line 57, in addTests
    for test in tests:
  File "C:\Users\chris\source\repos\arky\test\ark\test_v2.py", line 11, in __init__
    unittest.TestCase.__init__(self, args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\unittest\case.py", line 397, in __init__
    testMethod = getattr(self, methodName)
TypeError: getattr(): attribute name must be string

**Comment by Moustikitos** [comment]
I think it is related to the pip version defined in `travis.yml` file

**Comment by ciband** [comment]
I get the same behavior on my laptop (which is where my trace data came from) which is running what I believe to be the latest version of PIP.

It doesn't appear that the .travis.yml file calls out a PIP version, just pipenv.

I'm still a python n00b so I could be missing a connection somewhere.

If you have a theory on how to fix, I can certainly try to test.

**Comment by Moustikitos** [comment]
never mind, i found the bug : 
line 11 must be : ` unittest.TestCase.__init__(self, *args, **kwargs)`
will be corrected on the next PR

**Comment by ciband** [comment]
cool. glad you found it.
